/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:88d9dd83-d762-4f56-9332-32e2b266cd1b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dKZX11kJq",
    "aws_user_pools_web_client_id": "3saqdrj1b76fspkvn4al0me0ld",
    "oauth": {}
};


export default awsmobile;
